"""Generate an HTML report from sample or real recommendations."""

import argparse
import json
from datetime import datetime
from pathlib import Path


def _generate_html(recs: list[dict], project_id: str, out_path: Path) -> None:
    """Build a self-contained HTML report."""
    total_monthly = sum(r.get("estimated_savings_monthly", 0) for r in recs)
    total_yearly = sum(r.get("estimated_savings_monthly", 0) * 12 for r in recs)

    by_category: dict[str, list[dict]] = {}
    for r in recs:
        by_category.setdefault(r.get("category", "unknown"), []).append(r)

    severity_order = {"high": 0, "medium": 1, "low": 2}
    recs_sorted = sorted(recs, key=lambda r: (severity_order.get(r.get("severity", "low"), 2), -(r.get("estimated_savings_monthly", 0))))

    rows_html = ""
    for r in recs_sorted:
        sev = r.get("severity", "low")
        savings = r.get("estimated_savings_monthly", 0)
        row_color = {"high": "#ff4d4f", "medium": "#faad14", "low": "#52c41a"}.get(sev, "#888")
        sql_block = f'<pre style="background:#f5f5f5;padding:8px;margin:4px 0;font-size:12px;overflow-x:auto">{r.get("sql_code","")}</pre>' if r.get("sql_code") else ""
        rows_html += f"""
        <tr>
            <td><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:{row_color};margin-right:6px"></span>{sev.upper()}</td>
            <td>{r.get("category","")}</td>
            <td>{r.get("title","")}</td>
            <td>{r.get("description","")[:120]}…</td>
            <td style="text-align:right;font-weight:bold">${savings:,.2f}</td>
            <td>{r.get("confidence_score",0):.0%}</td>
        </tr>{sql_block}"""

    summary_html = ""
    for cat, items in by_category.items():
        cat_savings = sum(i.get("estimated_savings_monthly", 0) for i in items)
        summary_html += f'<div class="cat-card"><h4>{cat.replace("_"," ").title()}</h4><p>{len(items)} recommendation(s) · ${cat_savings:,.2f}/month</p></div>'

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>BQ FinOps Report — {project_id}</title>
<style>
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f0f2f5;color:#1a1a2e}}
  .header{{background:linear-gradient(135deg,#1a1a2e 0%,#16213e 100%);color:#fff;padding:32px 40px}}
  .header h1{{font-size:24px;font-weight:700}}
  .header p{{opacity:.7;margin-top:4px;font-size:14px}}
  .kpi-row{{display:flex;gap:16px;padding:24px 40px;flex-wrap:wrap}}
  .kpi{{background:#fff;border-radius:12px;padding:20px 28px;flex:1;min-width:180px;box-shadow:0 1px 4px rgba(0,0,0,.08)}}
  .kpi .label{{font-size:12px;color:#888;text-transform:uppercase;letter-spacing:.5px}}
  .kpi .value{{font-size:28px;font-weight:700;margin-top:4px}}
  .kpi .sub{{font-size:12px;color:#aaa;margin-top:2px}}
  .summary{{padding:0 40px 16px;display:flex;gap:12px;flex-wrap:wrap}}
  .cat-card{{background:#fff;border-radius:10px;padding:14px 20px;flex:1;min-width:200px;box-shadow:0 1px 3px rgba(0,0,0,.06)}}
  .cat-card h4{{font-size:13px;margin-bottom:4px}}
  .cat-card p{{font-size:12px;color:#666}}
  .table-wrap{{padding:16px 40px 40px}}
  table{{width:100%;border-collapse:collapse;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)}}
  th{{background:#16213e;color:#fff;font-size:12px;text-transform:uppercase;letter-spacing:.5px;padding:12px 16px;text-align:left}}
  td{{padding:12px 16px;border-bottom:1px solid #f0f0f0;font-size:13px;vertical-align:top}}
  tr:last-child td{{border-bottom:none}}
  tr:hover td{{background:#fafafa}}
  .footer{{text-align:center;padding:20px;color:#aaa;font-size:12px}}
</style>
</head>
<body>
<div class="header">
  <h1>BQ FinOps Agent — Report</h1>
  <p>Project: {project_id} · Generated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}</p>
</div>
<div class="kpi-row">
  <div class="kpi"><div class="label">Total Recommendations</div><div class="value">{len(recs)}</div></div>
  <div class="kpi"><div class="label">Est. Monthly Savings</div><div class="value" style="color:#52c41a">${total_monthly:,.2f}</div></div>
  <div class="kpi"><div class="label">Est. Yearly Savings</div><div class="value" style="color:#1677ff">${total_yearly:,.2f}</div></div>
  <div class="kpi"><div class="label">High Severity</div><div class="value" style="color:#ff4d4f">{sum(1 for r in recs if r.get('severity')=='high')}</div></div>
</div>
<div class="summary">{summary_html}</div>
<div class="table-wrap">
<table>
  <thead><tr><th>Severity</th><th>Category</th><th>Title</th><th>Description</th><th>Est. $/mo</th><th>Confidence</th></tr></thead>
  <tbody>{rows_html}</tbody>
</table>
</div>
<div class="footer">Generated by BQ FinOps Agent · GCP-native agentic AI demo</div>
</body></html>"""

    out_path.write_text(html, encoding="utf-8")
    print(f"[+] HTML report written to: {out_path}")


def cmd_report_html(args: argparse.Namespace) -> int:
    """Generate HTML report — works in sample mode without credentials."""
    import samples.fake_clients
    from samples.data import generate_sample_recommendations
    from config import Config
    config = Config.from_env()

    recs = generate_sample_recommendations()
    out_path = Path(args.output or f"bq_finops_report_{config.project_id or 'demo'}.html")
    _generate_html(recs, config.project_id or "demo", out_path)
    return 0


def cmd_report_real(args: argparse.Namespace, config: Config) -> None:
    """Original report from BigQuery storage."""
    from models.storage import BQStorage
    storage = BQStorage(config.project_id, config.location)
    recs = storage.get_recommendations(limit=args.limit)

    total_monthly = sum(r.estimated_savings_monthly for r in recs)
    total_yearly = sum(r.total_savings_yearly for r in recs)

    print(f"\n{'='*60}")
    print(f"BQ FinOps Report - {config.project_id}")
    print(f"{'='*60}")
    print(f"Total Recommendations: {len(recs)}")
    print(f"Estimated Monthly Savings: ${total_monthly:,.2f}")
    print(f"Estimated Yearly Savings: ${total_yearly:,.2f}")
    print(f"{'='*60}\n")

    for rec in recs[:args.limit]:
        print(f"[{rec.severity.value.upper()}] {rec.title}")
        print(f"  Category: {rec.category.value}")
        print(f"  Savings: ${rec.estimated_savings_monthly:,.2f}/month")
        print(f"  {rec.description[:100]}...\n")


def main() -> int:
    import argparse
    parser = argparse.ArgumentParser(description="BQ FinOps Agent")
    parser.add_argument("--mode", choices=["analyze", "report", "report-html"], default="analyze")
    parser.add_argument("--limit", type=int, default=20)
    parser.add_argument("--output", type=Path, help="Output path for HTML report")
    parser.add_argument("--config", type=Path, default=Path(".env"))
    parser.add_argument("--sample", action="store_true", help="Run with sample data (no GCP credentials needed)")

    args = parser.parse_args()

    if args.mode == "report-html":
        return cmd_report_html(args)

    config = Config.from_env()
    if not args.sample:
        errors = config.validate()
        if errors:
            print(f"Config errors: {errors}")
            return 1

    if args.mode == "analyze":
        import main as _m
        # re-run analyze inline
        from pipeline import FinOpsAgent
        agent = FinOpsAgent(config)
        result = agent.run()
        print(f"\n{'='*60}")
        print(f"Analysis Complete - {config.project_id}")
        print(f"{'='*60}")
        print(f"Total Recommendations: {result['total_recommendations']}")
        print(f"Estimated Monthly Savings: ${result['total_monthly_savings']:,.2f}")
        print(f"Saved to BigQuery: {result['saved_count']} records")
        print(f"{'='*60}\n")
    elif args.mode == "report":
        cmd_report_real(args, config)

    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
